- .rootlogon.C
- README.md
- compile.sh
- makeDisplays.py
- make_tree.C
- processRun.py
Automatic reading of sampling rate. Add veto channels to display. Allow forcing of channels to display. Add compiling script, with marking of version at compile time instead of run time. Fix processRun crash scenario."
[master a1f1c28] Automatic reading of sampling rate. Add veto channels to display. Allow forcing of channels to display. Add compiling script, with marking of version at compile time instead of run time. Fix processRun crash scenario.
> Updates to display, automatic reading of sampling rate. Bug fixes. Add compile script

- offlineProduction/scripts/transferFiles.py
> Added OSU as a transfer site

- Run3Detector/interface/OfflineFactory.h
- Run3Detector/scripts/printDatabase.py
- Run3Detector/scripts/processRuns.py
- Run3Detector/scripts/runOfflineFactory.py
- Run3Detector/setup.sh
- Run3Detector/src/OfflineFactory.cc
- Fixed type for clockCycles
- fixed matching when submitting
- Added TDC timing variables 
- Added time fit for pulses
> Various fixes to submission and matching

- Run3Detector/interface/OfflineFactory.h
- Run3Detector/scripts/runOfflineFactory.py
- Run3Detector/src/OfflineFactory.cc
> Drs processing

- Run3Detector/interface/OfflineFactory.h
- Run3Detector/scripts/runOfflineFactory.py
- Run3Detector/src/OfflineFactory.cc
Adds the run and file number to the tag so can quickly find out what runs/files are included when hadding
> minor tag update for convenience

- Run3Detector/src/OfflineFactory.cc
> Added the dynamicPedestal to output file

- Run3Detector/scripts/removeFiles.py
File removeFiles.py added to scripts directory. 
1. Checks if disk quota over threshold (90%)
2. If over threshold gets files and checks for them on MongoDB
3. Any file saved n times will be removed (n=2)
> File for removing data from milliDAQ

- Run3Detector/scripts/removeFiles.py
Files will only be removed if they are older than 24 hours.
> File removal now won't remove anything created in last 24 hours

- Run3Detector/analysis/utilities/README.md
- Run3Detector/analysis/utilities/condor_wrapper.sh
- Run3Detector/analysis/utilities/exampleLooperMultiprocess.py
- Run3Detector/analysis/utilities/run_jobs.py
This PR includes a new directory analysis/utilities. Inside of this directory I have put some files that are useful for submitting condor batch jobs.
1. run_jobs.py will create condor run scripts and submit jobs to a condor cluster.
2. condor_wrapper.sh is used to run the script and move the output files
3. exampleLooperMultiprocess.py is an example script for how to use the tool
> Condor Scripts

- Run3Detector/interface/OfflineFactory.h
- Run3Detector/scripts/runOfflineFactory.py
- Run3Detector/src/OfflineFactory.cc
Adds info to output file to quickly see if trigger matching run for this file
> Add matched t name

- Run3Detector/scripts/checkFiles.py
- Run3Detector/scripts/compareFiles.py
- Run3Detector/scripts/transferFiles.py
Bug fix in file transfer script. 
Add checkFiles.py to look for files that are not in mongoDB or daq pc. These file could be deleted unintentionally
> Fix Bug in FileTransfer Script

- Run3Detector/processTrees/OSU/matching_wrapper.py
- Run3Detector/processTrees/OSU/run_matchTriggerEvents.py
- Run3Detector/processTrees/OSU/run_processTrees.py
- Run3Detector/processTrees/OSU/wrapper.sh
- Run3Detector/singularity/createContainer.sh
- Run3Detector/singularity/mQContainer.def
Updates to singularity image to allow offline trigger matching. 
Scripts in processTrees/OSU to allow trigger matching offline.
Updates to scripts in processTrees/OSU to create offline trees
> Singularity Update

- Run3Detector/scripts/findEvents.py
- Run3Detector/scripts/makeEventDisplaysFromDraw.py
- Run3Detector/scripts/processRuns.py
- Run3Detector/src/OfflineFactory.cc
Usage:
python3 scripts/makeEventDisplaysFromDraw.py -t <tag> -s '<tcut string - must be inverted commas>' -r <run number> [-m <max events to draw (default 10)>]
for example:
python3 scripts/makeEventDisplaysFromDraw.py -t slabHits -s 'MaxIf$(time,chan==71&&ipulse==0)-MaxIf$(time,chan==75&&ipulse==0)>-25&&MaxIf$(time,chan==71&&ipulse==0)-MaxIf$(time,chan==75&&ipulse==0)<25&&MaxIf$(height,chan==71&&ipulse==0)>1200&&MaxIf$(height,chan==75&&ipulse==0)>1200' -r 920
draws through-going muons for run 920
> Script to make event displays from draw statement

- Run3Detector/scripts/makeOffineFiles.py
- Run3Detector/scripts/removeFiles.py
- Run3Detector/scripts/runMakeOfflineFiles.sh
New scripts to process trigger matching and offline file production on DAQ-00.
> updates to process trigger matching and offline files on daq-00

- Run3Detector/scripts/removeFiles.py
Bug fix for removing slab files
> Remove Slab Files

- Run3Detector/processTrees/OSU/combineOfflineFiles.py
- Run3Detector/processTrees/OSU/matching_wrapper.py
- Run3Detector/processTrees/OSU/milliqanTools/moveFiles.py
- Run3Detector/processTrees/OSU/milliqanTools/moveMilliQanFiles.sh
- Run3Detector/processTrees/OSU/milliqanTools/processOfflineTrees.sh
- Run3Detector/processTrees/OSU/milliqanTools/sourceRoot.sh
- Run3Detector/processTrees/OSU/run_matchTriggerEvents.py
- Run3Detector/processTrees/OSU/run_processTrees.py
- Run3Detector/processTrees/OSU/tree_wrapper.py
- Run3Detector/processTrees/OSU/wrapper.sh
- Run3Detector/scripts/printDatabase.py
updates to scripts to process matched and offline files at OSU
> Update osu processing

- Run3Detector/processTrees/OSU/milliqanTools/moveFiles.py
- Run3Detector/processTrees/OSU/milliqanTools/offlineTransfer.sh
- Run3Detector/processTrees/OSU/milliqanTools/run.sub
- Run3Detector/processTrees/OSU/milliqanTools/test.py
- Run3Detector/processTrees/OSU/milliqanTools/transferOfflineFiles.py
- Run3Detector/processTrees/OSU/milliqanTools/transferSimFiles.py
- Run3Detector/processTrees/OSU/run_matchTriggerEvents.py
- Run3Detector/processTrees/OSU/run_processTrees.py
- Run3Detector/processTrees/OSU/tree_wrapper.py
- Run3Detector/processTrees/OSU/wrapper.sh
- Run3Detector/scripts/transferOfflineFiles.py
This PR adds a script "transferOfflineFiles.py" to transfer all offline files produced at OSU to UCSB.
There are also some updates to the scripts used for processing files at OSU.
> Offline Transfer Script

- Run3Detector/scripts/changeLocation.py
Modifications to changeLocation.py script to allow updating of all file locations in mongoDB
> Change Locations Update

- Run3Detector/scripts/utilities.py
Add a list of file types to utilities (forgot to add on last PR)
> Add File Types

- Run3Detector/analysis/utilities/milliqanPlotter.py
Modified mqplotter to flatten only when necessary.
> Added axis=None to only flatten when necessary.

- Run3Detector/analysis/utilities/milliqanScheduler.py
- Run3Detector/analysis/utilities/withoutPlotter.py
Sometimes we only want to do a quick analysis without making plots.  I make changes on milliqanScheduller so that it can work without a plotter.
> make changes on milliqanScheduler, so it can work without plotter class

- Run3Detector/scripts/makeEventDisplaysFromDraw.py
needed updates to work with reorg of files at UCSB and with latest updates to tree making code
> updated event displays from draw

- Run3Detector/analysis/goodRunTools/checkMatching.py
- Run3Detector/analysis/goodRunTools/goodRun_wrapper.sh
- Run3Detector/analysis/goodRunTools/run_createGoodRunList.py
Add good run list tools to milliqan offline.
Good run list includes checks on
trigger matching (matched files and inclusion in offline data)
checks for all channels to be active (needs some edits due to dead channel 75)
board matching
default triggers
Produces two json files. One detailing all info of the runs and why they do/don't pass (checks.json) and one listing just the good runs to be used by producer (goodRuns.json)
> Good Runs List Tools

- Run3Detector/analysis/utilities/milliqanCuts.py
I accidentally deleted hightCut last time.
> bring back heightCut()

- Run3Detector/scripts/removeFiles.py
fixes the file removal script to use the new mongo db
also includes fix to handle files that have different config file naming (ex. MilliQan_Run1400.1_thresholdChange.root)
> fix file removal script
